//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifiedLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class TAC_ClassifiedContact
    {
        [DataMember]public int ContactId { get; set; }
        [DataMember]public string ContactName { get; set; }
        [DataMember]public string ContactPhone { get; set; }
        [DataMember]public string ContactCity { get; set; }
        [DataMember]public int ClassifiedId { get; set; }
        
        [DataMember]public virtual TAC_Classified TAC_Classified { get; set; }
    }
}
