//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAClassifiedLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    public partial class TAC_Classified
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAC_Classified()
        {
            this.TAC_ClassifiedContact = new HashSet<TAC_ClassifiedContact>();
        }
    
       [DataMember] public int ClassifiedId { get; set; }
       [DataMember] public string ClassifiedTitle { get; set; }
       [DataMember] public string Summary { get; set; }
       [DataMember] public string Description { get; set; }
       [DataMember] public string ClassifiedImage { get; set; }
       [DataMember] public decimal ClassifiedPrice { get; set; }
       [DataMember] public System.DateTime PostedDate { get; set; }
       [DataMember] public System.Guid CreatedBy { get; set; }
       
       [DataMember] public virtual TAC_User TAC_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       [DataMember] public virtual ICollection<TAC_ClassifiedContact> TAC_ClassifiedContact { get; set; }
    }
}
